### ISSUE TITLE
couple questions

### ISSUE THREAD

**Issue by whaley18** [bszek213/deepCFB#2]
1. For the xgboost model, how long does it take to create? I have a Mac and ran it overnight, and it never finished.
2. When interpreting the data, how would you see this outcome? Both teams have over a 90% chance of victory with the rolling median. I am not new to writing software but new to data analytics, so please bear with me if this is a simple question. Also, I am not running the data with the xgboost model as it did not finish creating overnight, so the prediction may be off. @bszek213 
![image](https://github.com/bszek213/deepCFB/assets/144848531/32fe2969-b75f-43bd-adc3-f8f66a93ccef)

**Comment by bszek213** [comment]
The xgboost usually takes a long time, as it has the underlying algorithm being a random forest, which is an ensembling approach. Therefore, xgboost is now an ensemble of an ensemble. With the hyperparameter tuning, it is running over 300 iterations of this algorithm.

Right now how I have it, each time is independent of each other. Which means that I am not actually comparing one team to another, as of right now. In the future, I am going to set up the data to compare one team's performance to the other team's performance. However, for right now, the outputs will be independent of each other, so one team can have a 0-100% probability and so could the other team.
