### ISSUE TITLE
PICKS

### ISSUE THREAD

**Issue by jrue00** [bszek213/deepCFB#4]
Would you be willing to add file to show the predicted picks, I am curious to see the outcome

**Comment by omar319** [comment]
I'm actually curious after running the commands which I have and generates the pkl files are those the files that have the analysis for the teams? I've tried opening them but the data seems corrupted.

**Comment by bszek213** [comment]
In the README, I provide an overview of the team's performance in the previous week. To do this, I analyze data from their previous game to predict their performance in the most recent game. I then compare the model's predictions with the actual outcome (win or loss). It's worth noting that the model's accuracy stands at approximately 85-87% for the top 35 teams.

**Comment by bszek213** [comment]
The .pkl files house models designed to generate features for the upcoming "hypothetical game" a team might play. To observe the analysis, you'll need to execute the deep_learn.py script with the 'test' argument.

**Comment by bszek213** [comment]
> I'm actually curious after running the commands which I have and generates the pkl files are those the files that have the analysis for the teams? I've tried opening them but the data seems corrupted.
